name: Logging the message on the console

on:
  push:
    branches :
      - main
      - temp
jobs:
  logging:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: logging the message in the runner console.
        run: echo "new msg logged."
  
  build_and_run:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build the Docker image
        run: docker build -t pradeep3014/github_actions:latest .

      - name: login into the docker hub
        run: |
          echo "${{secrets.REPO_TOKEN}}" | docker login -u pradeep3014 --password-stdin
  
      - name: pushing image into docker hub
        run: docker push pradeep3014/github_actions:latest