name: Logging the message on the console

on:
  push:
    branches :
      - main
      - temp
jobs:
  logging:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: logging the message in the runner console.
        run: echo "new msg logged."
  
  build_and_run:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build the Docker image
        run: docker build -t my_github_actions_repo_1:latest .

      - name: Run the container
        run: |
          docker run -d --name my-running-app -p 4000:4000 my_github_actions_repo_1:latest
  
 